dist:
  module: github.com/scopedb/telescope/services/gateway/collector
  name: telescope-otelcol
  description: Telescope telemetry collector
  output_path: ./_build
  version: 0.1.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.150.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.150.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.150.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.150.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.150.0

exporters:
  - gomod: github.com/scopedb/telescope/packages/scopedbexporter v0.0.0
    path: ../../../packages/scopedbexporter
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.150.0
